version: '3.8'

services:

  database:
    image: postgres:latest
    restart: always
    env_file:
      - env/development.env
  
  egg:
    build: app/
    restart: always
    volumes:
      - ./app:/egg/app
    ports:
      - 3000:3000
    env_file:
      - env/development.env
