version: '3.8'

services:

  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev-password
  
  egg:
    build: app/
    restart: always
    volumes:
      - ./app:/egg/app
    ports:
      - 3000:3000
