version: '3.8'

services:

  database:
    image: postgres:latest
    restart: always
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
    env_file:
      - env/development.env

  php-microservice:
    build: php-microservice/
    restart: always
    volumes:
      - ./app/public/php:/usr/local/apache2/htdocs/php
      - ./app/public/static:/usr/local/apache2/htdocs/static
    ports:
      - 3001:3001
  
  egg:
    build: app/
    restart: always
    volumes:
      - ./app:/egg/app
    ports:
      - 3000:3000
    env_file:
      - env/development.env
