version: '3.8'

networks:
  internal:
    driver: bridge

services:

  database:
    image: mysql:latest
    restart: always
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file:
      - env/development.env
    networks:
      - internal

  php-microservice:
    build: php-microservice/
    restart: always
    volumes:
      - ./app/public/php:/usr/local/apache2/htdocs/php
      - ./app/public/static:/usr/local/apache2/htdocs/static
    ports:
      - 3001:3001
    env_file:
      - env/development.env
    networks:
      - internal
  
  egg:
    build: app/
    restart: always
    volumes:
      - ./app:/egg/app
    ports:
      - 3000:3000
    env_file:
      - env/development.env
